version: "3.7"
services:
  nginx:
    build:
      context: "./docker/server/nginx"
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    networks:
      - demo_n1
    restart: always
    container_name: demo_os_nginx

  php-8.2:
    build:
      context: "./docker/php/php82"
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - nginx
    networks:
      - demo_n1
      - orangehrm_shared
    restart: always
    container_name: demo_os_dev_php82

networks:
  demo_n1:
  orangehrm_shared:
    external: true
volumes:
  sail-mysql:
    driver: local