services:
  taskflow-hr-app:
    container_name: taskflow-hr-app
    image: ghcr.io/justicea83/orangehrm:latest
    volumes:
      - php-sessions:/var/lib/php/sessions
    expose:
      - "9000"

  taskflow-hr-app-nginx:
    container_name: taskflow-hr-app-nginx
    image: ghcr.io/justicea83/orangehrm_nginx:latest
    depends_on:
      - taskflow-hr-app
    ports:
      - "6202:80"

volumes:
  php-sessions:
    driver: local