name: Build and Push docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
      IMAGE_NAME: orangehrm
      REPOSITORY: crossjobs
      GH_USERNAME: justicea83
      APP_ROOT: ghcr.io/justicea83

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "${{ vars.ENV_PROD }}" > .env
          cat .env  # Optional: Display the contents for debugging (remove in production)
          ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u $GH_USERNAME --password-stdin

      - name: Build and push images with Docker Compose
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_HOST }}
          command_timeout: 200m
          username: justicea83
          key: ${{ (env.CURRENT_ENV == 'dev' && secrets.VM_SSH_SECRET_DEV) || (env.CURRENT_ENV == 'prod' && secrets.VM_SSH_SECRET_PROD) }}
          script: |
            if [ $(docker ps -a | grep taskflow-hr-app | wc -l) -gt 0 ]; then
              docker stop taskflow-hr-app
              docker rm taskflow-hr-app
            fi
            docker image prune -a -f
            docker pull ghcr.io/justicea83/orangehrm:latest
            docker run -d --name taskflow-hr-app --network static-services_shared --restart unless-stopped ghcr.io/justicea83/orangehrm:latest
          

      - name: Deploy taskflow-hr-app-nginx to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_HOST }}
          command_timeout: 200m
          username: justicea83
          key: ${{ (env.CURRENT_ENV == 'dev' && secrets.VM_SSH_SECRET_DEV) || (env.CURRENT_ENV == 'prod' && secrets.VM_SSH_SECRET_PROD) }}
          script: |
            if [ $(docker ps -a | grep taskflow-hr-app-nginx | wc -l) -gt 0 ]; then
              docker stop taskflow-hr-app-nginx
              docker rm taskflow-hr-app-nginx
            fi
            docker image prune -a -f
            docker pull ghcr.io/justicea83/orangehrm_nginx:latest
            docker run -d -p 8000:80 --name taskflow-hr-app-nginx --network static-services_shared --restart unless-stopped ghcr.io/justicea83/orangehrm_nginx:latest

      - name: Cleanup .env file
        run: rm -rf .env